[general]
disableTypeErrors = false

[source_paths]
packages = [
    "astra/framework/src",
    "astra/runtime/src",
    "market-research"
]

[tool.pyrefly]
errors = { missing-override-decorator = "error" }

