"""
Storage persistence utilities.

Simple utility functions for persisting messages during agent/team execution.
"""

from observability import LogLevel, log, span, update_span


async def save_user_message(
    storage,
    thread_id: str | None,
    query: str,
    resource_type: str,
    resource_id: str,
    resource_name: str,
) -> str:
    """
    Save user message to storage and return the thread_id.

    If thread_id is not provided, creates a new thread.
    ID is auto-generated by the database backend.

    Args:
        storage: StorageClient instance or None
        thread_id: Optional thread ID
        query: User's query to save
        resource_type: Type of resource ("agent", "team", "stepper", "workflow")
        resource_id: ID of the resource
        resource_name: Human-readable name for display

    Returns:
        The thread_id to use for subsequent messages
    """
    if not storage:
        return thread_id or ""

    async with span(
        "storage.save_user_message",
        attributes={
            "resource_type": resource_type,
            "resource_id": resource_id,
            "message_length": len(query),
            "thread_provided": thread_id is not None,
        },
    ):
        # If thread_id provided, check if it exists
        if thread_id:
            async with span("storage.get_thread", attributes={"thread_id": thread_id}):
                thread = await storage.get_thread(thread_id)
            if thread is None:
                # Thread doesn't exist, create it with the provided ID
                title = query[:50] + ("..." if len(query) > 50 else "")
                async with span(
                    "storage.create_thread",
                    attributes={"thread_id": thread_id, "title_length": len(title)},
                ):
                    thread = await storage.create_thread(
                        thread_id=thread_id,
                        resource_type=resource_type,
                        resource_id=resource_id,
                        resource_name=resource_name,
                        title=title,
                    )
        else:
            # No thread_id provided, create new thread (store will generate ID)
            title = query[:50] + ("..." if len(query) > 50 else "")
            async with span(
                "storage.create_thread",
                attributes={"title_length": len(title)},
            ):
                thread = await storage.create_thread(
                    resource_type=resource_type,
                    resource_id=resource_id,
                    resource_name=resource_name,
                    title=title,
                )
            thread_id = thread.id

        assert thread_id is not None, "thread_id should be set after thread creation"

        async with span(
            "storage.add_message",
            attributes={"thread_id": thread_id, "role": "user"},
        ):
            await storage.add_message(thread_id, "user", query)

        update_span({"thread_id": thread_id})
        await log(LogLevel.DEBUG, "User message persisted", {"thread_id": thread_id})
        return thread_id


async def save_assistant_message(
    storage,
    thread_id: str | None,
    response: str,
    tool_calls: list[dict] | None = None,
    metadata: dict | None = None,
) -> None:
    """
    Save assistant message to storage and flush the queue.

    Args:
        storage: StorageClient instance or None
        thread_id: Thread ID
        response: Assistant's response to save
        tool_calls: Optional list of tool call dicts to persist
        metadata: Optional additional metadata
    """
    if storage and thread_id:
        async with span(
            "storage.save_assistant_message",
            attributes={
                "thread_id": thread_id,
                "message_length": len(response or ""),
                "tool_call_count": len(tool_calls or []),
            },
        ):
            async with span(
                "storage.add_message",
                attributes={"thread_id": thread_id, "role": "assistant"},
            ):
                await storage.add_message(
                    thread_id,
                    "assistant",
                    response,
                    tool_calls=tool_calls,
                    metadata=metadata,
                )
            async with span("storage.queue.flush"):
                await storage.queue.flush()
            await log(LogLevel.DEBUG, "Assistant message persisted", {"thread_id": thread_id})
